In [2]:
## Ejemplos a partir de:
## https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/

In [16]:
# Crear array 1 dimensional a partir de una lista
import numpy as np
list1 = [1,2,3,4]
arr1d = np.array(list1)
# se crea el array, pero no se muestra nada



In [12]:
# Imprmir el array y su tipo
print(arr1d)
print(type(arr1d))


['1' 'a' '2' 'b' '3' 'c' '4']
<class 'numpy.ndarray'>


In [17]:
# Tratar de sumar un entero a la lista
list1 + 2  # error

TypeError: can only concatenate list (not "int") to list

In [18]:
# Tratar de sumar un entero al array
arr1d + 2

array([3, 4, 5, 6])

In [25]:
# Crear un array 2 dimensional de enteros a partir de una lista de listas
list2 = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
arr2d = np.array(list2)
print(arr2d)
arr2d

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# Crear un array 2 dimensional de valores en coma flotante, con la misma lista de listas
arr2d_f = np.array(list2, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [27]:
# Convertir los elementos del array a tipo entero
arr2d_f.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# Convertir los elemenentos del array a tipo entero y luego a str, teniendo ahora un array de str
arr2d_f.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U11')

In [29]:
# Crear un array booleano
arr2d_b = np.array([1, 0, 10], dtype='bool')
arr2d_b


array([ True, False,  True])

In [13]:
# Crear un array que almacene tanto un entero como un str
arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

In [14]:
# Convertir el array de nuevo a lista
arr1d_obj.tolist()

[1, 'a']

In [15]:
# Crear un array 2 dimensional con 3 filas y 4 columnas
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
print(list2)
print(arr2)


[[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]]
[[ 1.  2.  3.  4.]
 [ 3.  4.  5.  6.]
 [ 5.  6.  7.  8.]]


In [16]:
# Ver la forma
print('Forma: ', arr2.shape)

Forma:  (3, 4)


In [17]:
# dtype (tipo)
print('Tipo: ', arr2.dtype)

Tipo:  float64


In [18]:
# tamaño
print('Tamaño: ', arr2.size)

Tamaño:  12


In [19]:
# Numero de dimension
print('Numero Dimensiones: ', arr2.ndim)


Numero Dimensiones:  2


In [20]:
# Imprimir el array
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [21]:
# Extraer las dos primeras filas y columnas
print(arr2[:2, :2])
print(list2[:2, :2])  # error

[[ 1.  2.]
 [ 3.  4.]]


TypeError: list indices must be integers or slices, not tuple

In [22]:
# Obtener el resultado booleano de aplicar una condición a cada elemento
b = arr2 > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [23]:
# Seleccionar los elementos que tienen esa condición como verdadera
arr2[b]

array([ 5.,  6.,  5.,  6.,  7.,  8.])

In [24]:
# Invertir el orden de las filas
arr2[::-1, ]

array([[ 5.,  6.,  7.,  8.],
       [ 3.,  4.,  5.,  6.],
       [ 1.,  2.,  3.,  4.]])

In [25]:
# Invertir el orden de las filas y las columnas
arr2[::-1, ::-1]

array([[ 8.,  7.,  6.,  5.],
       [ 6.,  5.,  4.,  3.],
       [ 4.,  3.,  2.,  1.]])

In [26]:
# Insertar un nan y un inf (nan: Not a Number)
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2


array([[  1.,   2.,   3.,   4.],
       [  3.,  nan,  inf,   6.],
       [  5.,   6.,   7.,   8.]])

In [27]:
# Reemplazar el nan y el inf por -1. No debe utilizarse >> arr2 == np.nan <<
missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1  
arr2


array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [28]:
# Media, maximo y mínimo
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  3.58333333333
Max value is:  8.0
Min value is:  -1.0


In [29]:
# Mínimo por columnas y por filas
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))

Column wise minimum:  [ 1. -1. -1.  4.]
Row wise minimum:  [ 1. -1.  5.]


In [30]:
# Suma acumulativa
np.cumsum(arr2)

array([  1.,   3.,   6.,  10.,  13.,  12.,  11.,  17.,  22.,  28.,  35.,
        43.])

In [31]:
# Asignar una parte de arr2 a arr2, no crea un nuevo array
arr2a = arr2[:2,:2]  
arr2a[:1, :1] = 100  # El cambio se refleja en arr2. arr2a es una vista, no una copia
arr2



array([[ 100.,    2.,    3.,    4.],
       [   3.,   -1.,   -1.,    6.],
       [   5.,    6.,    7.,    8.]])

In [32]:
# Si en lugar de asignar, copiamos de arr2 a arr2b ...
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 999  # el cambio no se refleja
arr2

array([[ 100.,    2.,    3.,    4.],
       [   3.,   -1.,   -1.,    6.],
       [   5.,    6.,    7.,    8.]])

In [33]:
# Cambiar la forma de un array 3x4 a 4x3
arr2.reshape(4, 3)

array([[ 100.,    2.,    3.],
       [   4.,    3.,   -1.],
       [  -1.,    6.,    5.],
       [   6.,    7.,    8.]])

In [34]:
# Flatten -aplanar- a array 1-dimensional
arr2.flatten()

array([ 100.,    2.,    3.,    4.,    3.,   -1.,   -1.,    6.,    5.,
          6.,    7.,    8.])

In [35]:
# Modificar el array aplanado no introduce cambios sobre el original
b1 = arr2.flatten()  
b1[0] = 9999
arr2

array([[ 100.,    2.,    3.,    4.],
       [   3.,   -1.,   -1.,    6.],
       [   5.,    6.,    7.,    8.]])

In [36]:
# Si en lugar de "flatten" hacemos "ravel", el array original si se ve modificado
b2 = arr2.ravel()  
b2[0] = 55 
arr2

array([[ 55.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [37]:
# El mínimo por defecto de un rango es cero.
print(np.arange(5))

[0 1 2 3 4]


In [38]:
# Y el paso por defecto de un rango es uno.
print(np.arange(0, 10))  

[0 1 2 3 4 5 6 7 8 9]


In [39]:
# De cero a nueve en pasos de dos:
print(np.arange(0, 10, 2))  

[0 2 4 6 8]


In [40]:
# De 10 a 1, en pasos de -1 (decreciente)
print(np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


In [41]:
# De 1 a 50 (ambos inclusive), 10 valores
np.linspace(start=1, stop=50, num=10, dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [42]:
# Limitar a 2 el número de decimales que se muestran
np.set_printoptions(precision=2)  

In [43]:
# Rango logaritmicamente equiespaciado esde 10^1 hasta 10^50, en 10 pasos, con base 10.
np.logspace(start=1, stop=50, num=10, base=10) 

array([  1.00e+01,   2.78e+06,   7.74e+11,   2.15e+17,   5.99e+22,
         1.67e+28,   4.64e+33,   1.29e+39,   3.59e+44,   1.00e+50])

In [44]:
np.zeros([2,2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [45]:
np.ones([2,2])

array([[ 1.,  1.],
       [ 1.,  1.]])

In [46]:
a = [1,2,3]
print(a)

[1, 2, 3]


In [47]:
# Tile: concatenación de lista
print('Tile:   ', np.tile(a, 2))

Tile:    [1 2 3 1 2 3]


In [48]:
# Repeat: Repetir cada elemento de una lista
print('Repeat: ', np.repeat(a, 2))

Repeat:  [1 1 2 2 3 3]


In [49]:
# Números aleatorios (por defecto, en el intervalo [0, 1), con forma 2, 2)
print(np.random.rand(2,2))

[[ 0.51  0.29]
 [ 0.02  0.68]]


In [50]:
# Distribución normal, por defecto media 0 y varianza unidad, con forma 2, 2
print(np.random.randn(2,2))

[[ 0.38  0.34]
 [ 2.16  0.24]]


In [51]:
# Enteros aleatorios en el intervalo [0, 10), con forma 2, 2
print(np.random.randint(0, 10, size=[2,2]))

[[8 0]
 [4 6]]


In [52]:
# Un número aleatorio obtenido de la uniforme [0,1)
print(np.random.random())

0.8748718082533287


In [53]:
# Números aleatorios de la uniforme [0,1) con forma 2, 2
print(np.random.random(size=[2,2]))


[[ 0.68  0.65]
 [ 0.05  0.77]]


In [54]:
# Elegir aleatoriamente y de forma equiprobable 10 elementos de una lista
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  

['o' 'a' 'a' 'i' 'e' 'u' 'e' 'a' 'e' 'o']


In [55]:
# Elegir aleatoriamente, y con unas probabilidades dadas, 10 elementos de una lista
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))  # picks more o's

['i' 'a' 'u' 'a' 'o' 'i' 'u' 'u' 'i' 'o']


In [56]:
# Fijar el estado de la semilla (pseudo)aleatoria
rn = np.random.RandomState(100)

# Generar números de la uniforme [0,1) con forma 2, 2. Tras fijar el estado de la semilla, el resultado es reproducible.
print(rn.rand(2,2))

[[ 0.54  0.28]
 [ 0.42  0.84]]


In [57]:
# Fijar de nuevo el estado de la semilla aleatoria
np.random.seed(100)


# # Generar números de la uniforme [0,1) con forma 2, 2. Son los mismos que antes.
print(np.random.rand(2,2))



[[ 0.54  0.28]
 [ 0.42  0.84]]


In [58]:
# Generar 10 elementos equiprobables en [0,10), tras fijar la semilla
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)
# Tomar los elementos de forma única, y su número de ocurrencias
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

[8 8 3 7 7 0 4 2 5 2]
Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]
